---
name: Gravatar-URL
version: 1.00
author: []
abstract: Make URLs for Gravatars from an email address
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Gravatar-URL
  license: http://dev.perl.org/licenses/
  repository: http://svn.schwern.org/svn/CPAN/Gravatar-URL
requires:
  Carp: 0
  Digest::MD5: 0
  URI::Escape: 0
  perl: 5.6.0
build_requires:
  Test::More: 0.4
provides:
  Gravatar::URL:
    file: lib/Gravatar/URL.pm
    version: 1.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - Gravatar
configure_requires:
  Module::Build: 0.2808
